----------------TẠO BẢNG----------------
CREATE DATABASE LESSON02
 ON  PRIMARY 
( NAME = N'LESSON02', FILENAME = N'D:\00.DATABASE\LESSON02.mdf' )
 LOG ON 
( NAME = N'LESSON02_log', FILENAME = N'D:\00.DATABASE\LESSON02_log.ldf' )
GO

USE LESSON02
GO
CREATE TABLE PRODUCT(
	ID BIGINT IDENTITY(1,1) CONSTRAINT PK_PRODUCT PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	PRICE FLOAT CHECK(PRICE >= 10000)
)
GO
CREATE TABLE ORDERS(
	ID BIGINT IDENTITY(1,1) CONSTRAINT PK_ORDERS PRIMARY KEY,
	USERNAME NVARCHAR(100),
	TOTAL FLOAT,
	ADDRESS NVARCHAR(255) DEFAULT(N'Vũ Ngọc Phan'),
	PHONE VARCHAR(15),
)
GO
CREATE TABLE ORDERS_DETAIL(
	ID BIGINT IDENTITY(1,1),
	PRODUCT_ID BIGINT CONSTRAINT FK_PRODUCT_ORDERSDETAIL FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)  ,
	ORDERS_ID BIGINT,
	PRICE FLOAT,
	QUATITY INT,
	CONSTRAINT PK_ORDERS_DETAIL PRIMARY KEY (ID,PRODUCT_ID,ORDERS_ID),
	CONSTRAINT FK_ORDERS_ORDERSDETAIL FOREIGN KEY(ORDERS_ID) REFERENCES ORDERS(ID)
)

CREATE TABLE USERS(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	USERNAME NVARCHAR(100),
	PHONE VARCHAR(15) UNIQUE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
)
GO
INSERT PRODUCT (NAME, PRICE) VALUES
('Iphone 15 promax',100000)
GO
INSERT ORDERS(USERNAME, TOTAL,ADDRESS,PHONE) VALUES
('Devmaster',100000,N'25 Vũ Ngọc Phan','012345678')

INSERT ORDERS(USERNAME, TOTAL,PHONE) VALUES
('Devmaster',100000,'012345678')
GO
SELECT * FROM ORDERS
GO
INSERT USERS(USERNAME, EMAIL,PHONE) VALUES
('Devmaster','devmaster@gmail.com','012345678')
GO
INSERT USERS(USERNAME, EMAIL,PHONE) VALUES
('Devmaster',NULL,'055345678')
GO
INSERT USERS(USERNAME, EMAIL,PHONE) VALUES
('Devmaster',NULL,'056345678')
GO

INSERT USERS(USERNAME, EMAIL,PHONE) VALUES
('Devmaster','devmaster2@gmail.com',NULL)
GO
